-- PARTE 1: Crear tabla de Reseñas (Reviews)
-- Si la tabla ya existe, no hará nada (IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar seguridad (RLS)
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Políticas de Reseñas (Reviews)
-- 1. Cualquiera puede ver las reseñas
DROP POLICY IF EXISTS "Reviews are viewable by everyone" ON public.reviews;
CREATE POLICY "Reviews are viewable by everyone" ON public.reviews
    FOR SELECT USING (true);

-- 2. Usuarios autenticados pueden crear reseñas
DROP POLICY IF EXISTS "Authenticated users can insert reviews" ON public.reviews;
CREATE POLICY "Authenticated users can insert reviews" ON public.reviews
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 3. Usuarios pueden editar sus propias reseñas
DROP POLICY IF EXISTS "Users can update own reviews" ON public.reviews;
CREATE POLICY "Users can update own reviews" ON public.reviews
    FOR UPDATE USING (auth.uid() = user_id);

-- 4. Usuarios pueden borrar sus propias reseñas
DROP POLICY IF EXISTS "Users can delete own reviews" ON public.reviews;
CREATE POLICY "Users can delete own reviews" ON public.reviews
    FOR DELETE USING (auth.uid() = user_id);


-- PARTE 2: Privacidad de Negocios (Opcional si ya funciona)
-- Asegurar que los negocios sean públicos para leer
DROP POLICY IF EXISTS "Businesses are viewable by everyone" ON public.businesses;
CREATE POLICY "Businesses are viewable by everyone" ON public.businesses
    FOR SELECT USING (true);

-- Asegurar que solo el dueño pueda editar
DROP POLICY IF EXISTS "Owners can update their own business" ON public.businesses;
CREATE POLICY "Owners can update their own business" ON public.businesses
    FOR UPDATE USING (auth.uid() = owner_id);
