-- 1. Create Reviews Table
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT REFERENCES public.businesses(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable RLS on Reviews
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 3. Reviews Policies

-- Everyone can read reviews
CREATE POLICY "Reviews are viewable by everyone" ON public.reviews
    FOR SELECT USING (true);

-- Authenticated users can insert reviews
CREATE POLICY "Authenticated users can insert reviews" ON public.reviews
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can update their own reviews
CREATE POLICY "Users can update own reviews" ON public.reviews
    FOR UPDATE USING (auth.uid() = user_id);

-- Users can delete their own reviews
CREATE POLICY "Users can delete own reviews" ON public.reviews
    FOR DELETE USING (auth.uid() = user_id);

-- Admins can manage all reviews
CREATE POLICY "Admins can manage all reviews" ON public.reviews
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid()
            AND profiles.role = 'admin'
        )
    );

-- 4. Business Privacy Policies (Refining existing ones)

-- Ensure businesses are viewable by everyone (Public Directory)
-- We drop existing select policy if it exists to avoid conflicts, or just add if missing.
-- Safest is to create if not exists.
DROP POLICY IF EXISTS "Businesses are viewable by everyone" ON public.businesses;
CREATE POLICY "Businesses are viewable by everyone" ON public.businesses
    FOR SELECT USING (true);

-- Ensure only owners can update their business
-- (Existing policy "Owners can update their own business" might exist, we refine it)
DROP POLICY IF EXISTS "Owners can update their own business" ON public.businesses;
CREATE POLICY "Owners can update their own business" ON public.businesses
    FOR UPDATE USING (auth.uid() = owner_id);

-- Ensure owners CANNOT select other businesses' private data?
-- Since we allow SELECT (true) for everyone, owners can see everything in the 'businesses' table.
-- If there are private columns (e.g. revenue), they should be in a separate table or use column-level security.
-- For now, 'businesses' table seems to contain public info (name, address, etc).
-- So SELECT (true) is correct for the directory functionality.

-- 5. Leads Privacy
-- Ensure leads are only visible to Admins (and maybe the creator?)
DROP POLICY IF EXISTS "Leads are viewable by admins only" ON public.leads;
CREATE POLICY "Leads are viewable by admins only" ON public.leads
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid()
            AND profiles.role = 'admin'
        )
    );
